export const ALL_BUG_DATA_REQUEST = 'ALL_BUG_DATA_REQUEST'
export const ALL_BUG_DATA_SUCCESS = 'ALL_BUG_DATA_SUCCESS'
export const ALL_BUG_DATA_FAIL = 'ALL_BUG_DATA_FAIL'
export const ALL_BUG_DATA_LOGOUT = 'ALL_BUG_DATA_REMOVE'

export const BUG_PROJECT_REQUEST = 'BUG_PROJECT_REQUEST'
export const BUG_PROJECT_SUCCESS = 'BUG_PROJECT_SUCCESS'
export const BUG_PROJECT_FAIL = 'BUG_PROJECT_FAIL'
export const BUG_PROJECT_LOGOUT = 'BUG_PROJECT_LOGOUT'

export const UPDATE_BUG_REQUEST = 'UPDATE_STATUS_BUG_REQUEST'
export const UPDATE_BUG_SUCCESS = 'UPDATE_STATUS_BUG_SUCCESS'
export const UPDATE_BUG_FAIL = 'UPDATE_STATUS_BUG_FAIL'

export const ADD_BUG_REQUEST = 'ADD_BUG_REQUEST'
export const ADD_BUG_SUCCESS = 'ADD_BUG_SUCCESS'
export const ADD_BUG_FAIL = 'ADD_BUG_FAIL'


export const SELECTED_BUG = 'SELECTED_BUG'
export const REMOVE_SELECTED_BUG = 'REMOVE_SELECTED_BUG'     

export const BUG_HISTORY_REQUEST =  'BUG_HISTORY_REQUEST'
export const BUG_HISTORY_SUCCESS = 'BUG_HISTORY_SUCCESS '
export const BUG_HISTORY_FAIL = 'BUG_HISTORY_FAIL'
export const BUG_HISTORY_LOGOUT = 'BUG_HISTORY_LOGOUT'

export const BUG_COMMENT_REQUEST =  'BUG_COMMENT_REQUEST'
export const BUG_COMMENT_SUCCESS = 'BUG_COMMENT_SUCCESS '
export const BUG_COMMENT_FAIL = 'BUG_COMMENT_FAIL'
export const BUG_COMMENT_LOGOUT = 'BUG_COMMENT_LOGOUT'


export const ARCHIVED_BUG_REQUEST = 'ARCHIVED_BUG_REQUEST'
export const ARCHIVED_BUG_SUCCESS = 'ARCHIVED_BUG_SUCCESS'
export const ARCHIVED_BUG_FAIL = 'ARCHIVED_BUG_FAIL'
export const ARCHIVED_BUG_REMOVE = 'ARCHIVED_BUG_REMOVE'

