export const INVITATION_USER_REQUEST = 'INVITATION_USER_REQUEST'
export const INVITATION_USER_SUCCESS = 'INVITATION_USER_SUCCESS'
export const INVITATION_USER_FAIL = 'INVITATION_USER_FAIL'
export const INVITATION_USER_REMOVE = 'INVITATION_USER_REMOVE'