export const PROJECT_DATA_REQUEST = 'PROJECT_DATA_REQUEST'
export const PROJECT_DATA_SUCCESS = 'PROJECT_DATA_SUCCESS'
export const PROJECT_DATA_FAIL = 'PROJECT_DATA_FAIL'
export const PROJECT_DATA_LOGOUT = 'PROJECT_DATA_REMOVE'

export const PROJECT_DETAILS_REQUEST = 'PROJECT_DETAILS_REQUEST'
export const PROJECT_DETAILS_SUCCESS = 'PROJECT_DETAILS_SUCCESS'
export const PROJECT_DETAILS_FAIL = 'PROJECT_DETAILS_FAIL'
export const PROJECT_DETAILS_DELETE = 'PROJECT_DETAILS_DELETE'

export const SELECT_PROJECT = 'SELECT_PROJECT'
export const REMOVE_SELECT_PROJECT= 'REMOVE_SELECT_PROJECT'

export const CREATE_PROJECT_REQUEST = 'CREATE_PROJECT_REQUEST'
export const CREATE_PROJECT_SUCCESS = 'CREATE_PROJECT_SUCCESS'
export const CREATE_PROJECT_FAIL = 'CREATE_PROJECT_FAIL'


export const ARCHIVED_PROJECT_REQUEST = 'ARCHIVED_PROJECT_REQUEST'
export const ARCHIVED_PROJECT_SUCCESS = 'ARCHIVED_PROJECT_SUCCESS'
export const ARCHIVED_PROJECT_FAIL = 'ARCHIVED_PROJECT_FAIL'
export const ARCHIVED_PROJECT_REMOVE = 'ARCHIVED_PROJECT_REMOVE'


