export const TOKEN_USER_REQUEST = 'TOKEN_USER_REQUEST'
export const TOKEN_USER_SUCCESS = 'TOKEN_USER_SUCCESS'
export const TOKEN_USER_FAIL = 'TOKEN_USER_FAIL'
export const TOKEN_USER_REMOVE = 'TOKEN_USER_REMOVE'

export const USER_DATA_REQUEST = 'USER_DATA_REQUEST'
export const USER_DATA_SUCCESS = 'USER_DATA_SUCCESS'
export const USER_DATA_FAIL = 'USER_DATA_FAIL'
export const USER_DATA_LOGOUT = 'USER_DATA_LOGOUT'

export const INVITATION_REQUEST = 'INVITATION_REQUEST'
export const INVITATION_SUCCESS = 'INVITATION_SUCCESS'
export const INVITATION_FAIL = 'INVITATION_FAIL'


export const ALL_INVITATION_BY_ADMIN_USER_REQUEST = 'ALL_INVITATION_BY_ADMIN_USER_REQUEST'
export const ALL_INVITATION_BY_ADMIN_USER_SUCCESS = 'ALL_INVITATION_BY_ADMIN_USER_SUCCESS'
export const ALL_INVITATION_BY_ADMIN_USER_FAIL = 'ALL_INVITATION_BY_ADMIN_USER_FAIL'

export const REMOVE_SELECTED_GUEST_USERS = 'REMOVE_SELECTED_GUEST_USERS'


export const SELECTED_ROLE_GUEST_USER = 'SELECTED_ROLE_GUEST_USER'
export const REMOVE_ROLE_GUEST_USER = 'REMOVE_ROLE_GUEST_USER'
